server:
  port: 8080

spring:
  application:
    name: OCP17Chapter7Template
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: on
      path: /h2-console

springdoc:
  swagger-ui:
    enabled: on